### ISSUE TITLE
Running Secondary MongoDB install

### ISSUE THREAD

**Issue by moderndeveloperllc** [percona/percona-server-mongodb-packaging#8]
@abychko Based on the code in the init.d file calling the helper script, and code in the helper script, there appears to be no way to run a secondary install of mongod via the init.d structure. The helper is including hardcoded paths for PID and .conf files. Would I have to create a copy of the helper script and change the paths there in addition to the init.d file?

**Comment by moderndeveloperllc** [comment]
@EvgeniyPatlan Just curious if there is any interest in changing any of this.

**Comment by EvgeniyPatlan** [comment]
Hi @moderndeveloperllc !
Thank you for your report.
I have created JIRA issue to check this issue.
Here is the link to it: https://jira.percona.com/browse/PSMDB-319

**Comment by moderndeveloperllc** [comment]
@EvgeniyPatlan Thanks. Didn't know I could have put it there. I'll close this.
